name: rider
description: My new Dart CLI package
version: 0.0.1
repository: https://github.com/Erengun/Rider

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.4.2
  cli_completion: ^0.5.0
  mason_logger: ^0.2.12
  package_config: ^2.1.0
  path: ^1.9.0
  pub_updater: ">=0.4.0 <0.6.0"

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0